---
- name: configure a basic webserver
  hosts: webservers
  become: true
  tasks:
    - name: ensure httpd package is present
      yum:
        name: httpd
        state: present

    - name: start and enable the httpd service
      service:
        name: httpd
        state: started
        enabled: true #persistent across reboots

    - name: allow port 80/tcp in the firewall
      firewalld:
        port: 80/tcp
        permanent: true
        immediate: true
        state: enabled

    - name: deploy an index.html from index.html.j2
      template:
        src: index.html.j2
        dest: /var/www/html/index.html
